version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: eflo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: eflo
    ports:
      - "3306:3306"
    volumes:
      - eflo_mysql_data:/var/lib/mysql

volumes:
  eflo_mysql_data:

